<?php // includes/footer.php ?>
</div> <!-- end flex-1 overflow-hidden -->

</div> <!-- end flex flex-col -->

<!-- Performance: Defered Search & Global Scripts -->
<script>
    document.addEventListener('DOMContentLoaded', () => {
        const searchInput = document.getElementById('mainSearch');
        const resultsContainer = document.getElementById('searchResults');
        const toolsData = [
            <?php
            if (isset($tools)) {
                foreach ($tools as $slug => $data) {
                    $cat = $data['category'] ?? 'uncategorized';
                    echo "{ name: '" . addslashes($data['name']) . "', slug: '$slug', category: '$cat', icon: '" . ($data['icon'] ?? 'fa-cube') . "', desc: '" . addslashes($data['desc'] ?? '') . "' },";
                }
            }
            ?>
        ];

        if (searchInput) {
            searchInput.addEventListener('input', (e) => {
                const query = e.target.value.toLowerCase().trim();
                if (query.length === 0) { resultsContainer.classList.add('hidden'); return; }
                const filtered = toolsData.filter(tool => tool.name.toLowerCase().includes(query) || tool.desc.toLowerCase().includes(query));
                if (filtered.length > 0) {
                    resultsContainer.innerHTML = filtered.slice(0, 10).map(tool => `
                        <a href="<?php echo url('tools/'); ?>${tool.category}/${tool.slug}" class="flex items-center p-4 hover:bg-primary/5 dark:hover:bg-primary/5 border-b border-gray-50 dark:border-white/5 last:border-0 transition-all group">
                            <div class="w-10 h-10 rounded-2xl bg-gray-100 dark:bg-gray-800 flex items-center justify-center text-gray-500 group-hover:bg-primary group-hover:text-white transition-all shadow-inner">
                                <i class="fas ${tool.icon}"></i>
                            </div>
                            <div class="ml-4">
                                <h4 class="text-sm font-black text-secondary dark:text-white group-hover:text-primary transition-colors">${tool.name}</h4>
                                <p class="text-[10px] text-gray-500 dark:text-gray-400 font-medium line-clamp-1 opacity-70">${tool.desc}</p>
                            </div>
                        </a>
                    `).join('');
                    resultsContainer.classList.remove('hidden');
                }
            });
        }

        // Global Download Helper
        window.snipToolsDownload = function (content, filename, isText = false) {
            const prefixedFilename = "SnipTools - " + filename;
            let finalContent = content;
            if (isText && typeof content === 'string') {
                const date = new Date().toLocaleString();
                finalContent = `--------------------------------------------------\nGenerated by: SnipTools\nURL: ${window.location.origin}\nDate: ${date}\n--------------------------------------------------\n\n` + content;
            }
            const blob = (content instanceof Blob) ? content : new Blob([finalContent], { type: isText ? 'text/plain' : 'application/octet-stream' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a'); a.href = url; a.download = prefixedFilename;
            document.body.appendChild(a); a.click(); document.body.removeChild(a);
            setTimeout(() => URL.revokeObjectURL(url), 100);
        };
    });
</script>

<link rel="icon" href="<?php echo url('favicon.ico'); ?>" type="image/x-icon">
<link rel="manifest" href="<?php echo url('manifest.json'); ?>">
<?php
// Inject Head Script if enabled (Moved to footer for FCP benefit)
$adsEnabled = $settings['ads_enabled'] ?? '1';
if ($adsEnabled === '1' && !empty($settings['ad_code_head'])) {
    echo $settings['ad_code_head'];
}
?>
<?php include_once __DIR__ . '/toast_provider.php'; ?>

<script>
    // Theme Management
    const applyTheme = () => {
        if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            document.documentElement.classList.add('dark')
        } else {
            document.documentElement.classList.remove('dark')
        }
    };
    applyTheme();

    const toggleTheme = () => {
        const isDark = document.documentElement.classList.toggle('dark');
        localStorage.theme = isDark ? 'dark' : 'light';
    };

    const darkModeBtnHeader = document.getElementById('darkModeToggleHeader');
    const darkModeBtnSidebar = document.getElementById('darkModeToggleSidebar');

    if (darkModeBtnHeader) darkModeBtnHeader.addEventListener('click', toggleTheme);
    if (darkModeBtnSidebar) darkModeBtnSidebar.addEventListener('click', toggleTheme);

    // Sidebar Desktop Logic
    const sidebar = document.getElementById('sidebar');
    const sidebarCollapseBtn = document.getElementById('sidebarCollapseBtn');

    const toggleSidebar = () => {
        if (sidebar) {
            sidebar.classList.toggle('collapsed');
            localStorage.sidebarCollapsed = sidebar.classList.contains('collapsed');
        }
    };

    if (sidebarCollapseBtn) {
        sidebarCollapseBtn.addEventListener('click', toggleSidebar);
    }

    // Restore sidebar state
    if (localStorage.sidebarCollapsed === 'true' && sidebar) {
        sidebar.classList.add('collapsed');
    }

    // Mobile Sidebar Logic
    const sidebarMobileToggle = document.getElementById('sidebarToggleMobile');
    const sidebarOverlay = document.getElementById('sidebarOverlay');

    const toggleMobileSidebar = () => {
        if (sidebar) sidebar.classList.toggle('-translate-x-full');
        if (sidebarOverlay) sidebarOverlay.classList.toggle('hidden');
    };

    if (sidebarMobileToggle) sidebarMobileToggle.addEventListener('click', toggleMobileSidebar);
    if (sidebarOverlay) sidebarOverlay.addEventListener('click', toggleMobileSidebar);

    // Keyboard Shortcuts (/)
    window.addEventListener('keydown', (e) => {
        if (e.key === '/' && document.activeElement.tagName !== 'INPUT' && document.activeElement.tagName !== 'TEXTAREA') {
            e.preventDefault();
            const searchInput = document.getElementById('mainSearch');
            if (searchInput) {
                searchInput.focus();
                searchInput.select();
            }
        }
    });
</script>
</body>

</html>